---
- name: Set up new VPC for app servers
  ec2_vpc_net:
    state: present
    region: "{{ region }}"
    cidr_block: 172.16.0.0/16
    name: "{{ team_name }}-vpc"
    tags:
      tool: ansible
  register: net

- name: Set up subnets
  ec2_vpc_subnet:
    state: present
    region: "{{ region }}"
    az: "{{ region }}{{ item.az }}"
    vpc_id: "{{ net.vpc.id }}"
    cidr: "{{ item.cidr }}"
    resource_tags:
      tool: ansible
      Name: "subnet-{{ item.az }}"
  with_items:
    - az: a
      cidr: "172.16.1.0/24"
    - az: b
      cidr: "172.16.2.0/24"

- name: Grant public access via an internet gateway
  ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ net.vpc.id }}"
    state: present
  register: gateway

- ec2_vpc_route_table:
    region: "{{ region }}"
    vpc_id: "{{ net.vpc.id }}"
    subnets:
      - "172.16.1.0/24"
      - "172.16.2.0/24"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ gateway.gateway_id }}"


- debug: msg="Created VPC named unicorn-vpc with 2 available subnets"
- debug: msg="{{ net.vpc.id }}"
- ec2_group:
    name: webservers
    region: "{{ region }}"
    description: Security group to allow public web traffic to the unicorn.rentals API
    vpc_id: "{{ net.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 5000
        to_port: 5000
        cidr_ip: 0.0.0.0/0
  register: web_sg
- debug: msg="Created VPC security group called webservers, ID {{ web_sg.group_id }} to take web traffic"
- ec2_group:
    name: public-ssh
    region: "{{ region }}"
    description: Security group for public SSH traffic (you may want to restrict this a bit...)
    vpc_id: "{{ net.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: ssh_sg
- debug: msg="Created VPC security group called public-ssh, ID {{ ssh_sg.group_id }} for granting SSH access to servers."
